spring:
  application:
    name: spring-ai
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true  

  web:
    locale: pt_BR
    locale-resolver: fixed

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1:8b

    openai:
      api-key: ${OPENAI_API_KEY}

    chat:
      client:
        enabled: false    

server:
  port: 9292
